# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt_factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
