# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt_factory', '0002_design_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='ascii_img',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
