# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirt_factory', '0003_design_ascii_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='ascii_img',
            new_name='ascii_str',
        ),
        migrations.RenameField(
            model_name='design',
            old_name='image',
            new_name='input_img_file',
        ),
    ]
