# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt_factory', '0004_auto_20160526_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.TextField(unique=True)),
                ('comment', models.TextField()),
                ('time_stamp', models.DateTimeField()),
                ('input_img_file', models.ImageField(upload_to='')),
                ('ascii_str', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Design',
        ),
    ]
