# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt_factory', '0005_auto_20160527_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirtdesign',
            name='design_name',
            field=models.TextField(),
        ),
    ]
